## NumPy

In [219]:
import numpy as np

# DataType and Attributes

NumPy's main datatype is the ndarray (n-dimensional array).
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving 
the size of the array along each dimension.


In [220]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [221]:
a1.shape

(3,)

In [222]:
a1.dtype

dtype('int64')

In [223]:
type(a1)

numpy.ndarray

In [224]:
a2 = np.array([[1, 2.3, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [225]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [226]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [227]:
a2.shape

(2, 3)

In [228]:
a3.shape

(2, 2, 3)

In [229]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [230]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [231]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [232]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from NumPy arrays

In [233]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.0
1  4.0  5.0  6.0

# 2. Creating Arrays

In [234]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [235]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [236]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [237]:
range_array = np.arange(0, 50, 5)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [238]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 6, 8, 4, 6],
       [9, 8, 5, 0, 2],
       [3, 5, 3, 9, 6]])

In [239]:
random_array.shape, random_array.size, random_array.ndim

((3, 5), 15, 2)

In [240]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.52929245, 0.56482311, 0.833549  ],
       [0.06281332, 0.60636662, 0.50361274],
       [0.16029869, 0.14544548, 0.63784086],
       [0.88290614, 0.03286581, 0.4280219 ],
       [0.87789307, 0.47650708, 0.36757054]])

In [241]:
random_array2.shape, random_array2.size, random_array2.ndim

((5, 3), 15, 2)

In [242]:
random_array3 = np.random.rand(4, 2)
random_array3

array([[0.24065025, 0.04823178],
       [0.17516678, 0.55677543],
       [0.53008548, 0.54422155],
       [0.29905275, 0.86542403]])

In [243]:
random_array3.shape, random_array3.size, random_array3.ndim

((4, 2), 8, 2)

In [244]:
# Pseudo Random numbers
# np.random.seed()

In [245]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [246]:
np.random.seed(8)
random_array5 = np.random.random((3, 4))
random_array5

array([[0.8734294 , 0.96854066, 0.86919454, 0.53085569],
       [0.23272833, 0.0113988 , 0.43046882, 0.40235136],
       [0.52267467, 0.4783918 , 0.55535647, 0.54338602]])

# 3.Viewing arrays and matrices

In [247]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [248]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
a1

array([1, 2, 3])

In [250]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [251]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [252]:
a1[0], a2[0], a3[0]

(np.int64(1),
 array([1. , 2.3, 3. ]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [253]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [254]:
a3[:, :, 0]

array([[ 1,  4],
       [ 7, 10]])

In [255]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 2, 6, 8, 9],
         [3, 4, 5, 5, 7],
         [9, 2, 6, 9, 5],
         [1, 6, 4, 5, 8]],

        [[0, 7, 2, 6, 7],
         [4, 8, 9, 6, 4],
         [5, 2, 2, 6, 6],
         [6, 7, 9, 6, 0]],

        [[9, 2, 7, 9, 2],
         [6, 3, 0, 9, 0],
         [0, 6, 9, 7, 4],
         [7, 9, 4, 8, 2]]],


       [[[7, 2, 8, 6, 5],
         [2, 3, 3, 8, 7],
         [9, 7, 3, 8, 0],
         [7, 3, 0, 9, 0]],

        [[1, 2, 6, 7, 3],
         [8, 2, 9, 6, 5],
         [1, 3, 0, 0, 8],
         [6, 7, 8, 1, 0]],

        [[8, 9, 5, 2, 2],
         [2, 7, 7, 7, 6],
         [0, 3, 2, 4, 1],
         [5, 6, 3, 3, 0]]]])

In [256]:
a4.shape, a4.ndim, a4.size, a4.dtype

((2, 3, 4, 5), 4, 120, dtype('int64'))

In [257]:
a4[:, :, :1, :]

array([[[[2, 2, 6, 8, 9]],

        [[0, 7, 2, 6, 7]],

        [[9, 2, 7, 9, 2]]],


       [[[7, 2, 8, 6, 5]],

        [[1, 2, 6, 7, 3]],

        [[8, 9, 5, 2, 2]]]])

In [258]:
a4[1, 0, 0]

array([7, 2, 8, 6, 5])

# 4.Manipulating and Computing on NumPy Arrays

### Arithmetic

In [259]:
a1

array([1, 2, 3])

In [260]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [261]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [262]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [263]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [264]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [265]:
a1

array([1, 2, 3])

In [266]:
a1 + a2

array([[2. , 4.3, 6. ],
       [5. , 7. , 9. ]])

In [267]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [268]:
a2 * a3

array([[[ 1. ,  4.6,  9. ],
        [16. , 25. , 36. ]],

       [[ 7. , 18.4, 27. ],
        [40. , 55. , 72. ]]])

In [269]:
a4

array([[[[2, 2, 6, 8, 9],
         [3, 4, 5, 5, 7],
         [9, 2, 6, 9, 5],
         [1, 6, 4, 5, 8]],

        [[0, 7, 2, 6, 7],
         [4, 8, 9, 6, 4],
         [5, 2, 2, 6, 6],
         [6, 7, 9, 6, 0]],

        [[9, 2, 7, 9, 2],
         [6, 3, 0, 9, 0],
         [0, 6, 9, 7, 4],
         [7, 9, 4, 8, 2]]],


       [[[7, 2, 8, 6, 5],
         [2, 3, 3, 8, 7],
         [9, 7, 3, 8, 0],
         [7, 3, 0, 9, 0]],

        [[1, 2, 6, 7, 3],
         [8, 2, 9, 6, 5],
         [1, 3, 0, 0, 8],
         [6, 7, 8, 1, 0]],

        [[8, 9, 5, 2, 2],
         [2, 7, 7, 7, 6],
         [0, 3, 2, 4, 1],
         [5, 6, 3, 3, 0]]]])

In [270]:
# a2 + a4 error

In [271]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [272]:
a2_Fix = a2[:, :, np.newaxis, np.newaxis]
a2_Fix

array([[[[1. ]],

        [[2.3]],

        [[3. ]]],


       [[[4. ]],

        [[5. ]],

        [[6. ]]]])

In [273]:
a2_Fix + a4

array([[[[ 3. ,  3. ,  7. ,  9. , 10. ],
         [ 4. ,  5. ,  6. ,  6. ,  8. ],
         [10. ,  3. ,  7. , 10. ,  6. ],
         [ 2. ,  7. ,  5. ,  6. ,  9. ]],

        [[ 2.3,  9.3,  4.3,  8.3,  9.3],
         [ 6.3, 10.3, 11.3,  8.3,  6.3],
         [ 7.3,  4.3,  4.3,  8.3,  8.3],
         [ 8.3,  9.3, 11.3,  8.3,  2.3]],

        [[12. ,  5. , 10. , 12. ,  5. ],
         [ 9. ,  6. ,  3. , 12. ,  3. ],
         [ 3. ,  9. , 12. , 10. ,  7. ],
         [10. , 12. ,  7. , 11. ,  5. ]]],


       [[[11. ,  6. , 12. , 10. ,  9. ],
         [ 6. ,  7. ,  7. , 12. , 11. ],
         [13. , 11. ,  7. , 12. ,  4. ],
         [11. ,  7. ,  4. , 13. ,  4. ]],

        [[ 6. ,  7. , 11. , 12. ,  8. ],
         [13. ,  7. , 14. , 11. , 10. ],
         [ 6. ,  8. ,  5. ,  5. , 13. ],
         [11. , 12. , 13. ,  6. ,  5. ]],

        [[14. , 15. , 11. ,  8. ,  8. ],
         [ 8. , 13. , 13. , 13. , 12. ],
         [ 6. ,  9. ,  8. , 10. ,  7. ],
         [11. , 12. ,  9. ,  9. ,  6. ]]]])

In [274]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [275]:
a1 / a2

array([[1.        , 0.86956522, 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [276]:
a1 // a2 # Floor division removes the decimals (Rounds down)

array([[1., 0., 1.],
       [0., 0., 0.]])

In [277]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [278]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])