## NumPy

In [4]:
import numpy as np

# DataType and Attributes

NumPy's main datatype is the ndarray (n-dimensional array).
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving 
the size of the array along each dimension.


In [5]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
a1.shape

(3,)

In [7]:
a1.dtype

dtype('int64')

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2.3, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 2, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from NumPy arrays

In [18]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.0
1  4.0  5.0  6.0

# 2. Creating Arrays

In [19]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [21]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
range_array = np.arange(0, 50, 5)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 4, 7, 8, 2],
       [9, 1, 1, 4, 9],
       [0, 2, 4, 4, 6]])

In [24]:
random_array.shape, random_array.size, random_array.ndim

((3, 5), 15, 2)

In [25]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.63770535, 0.658138  , 0.48843772],
       [0.45077785, 0.44640857, 0.33907652],
       [0.6934968 , 0.96885698, 0.32203753],
       [0.31606436, 0.31018511, 0.45504561],
       [0.73609006, 0.50460535, 0.91556859]])

In [26]:
random_array2.shape, random_array2.size, random_array2.ndim

((5, 3), 15, 2)

In [27]:
random_array3 = np.random.rand(4, 2)
random_array3

array([[0.07024313, 0.00426344],
       [0.88329851, 0.33432456],
       [0.89527901, 0.33112226],
       [0.65961956, 0.90573462]])

In [28]:
random_array3.shape, random_array3.size, random_array3.ndim

((4, 2), 8, 2)

In [29]:
# Pseudo Random numbers
# np.random.seed()

In [30]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
np.random.seed(8)
random_array5 = np.random.random((3, 4))
random_array5

array([[0.8734294 , 0.96854066, 0.86919454, 0.53085569],
       [0.23272833, 0.0113988 , 0.43046882, 0.40235136],
       [0.52267467, 0.4783918 , 0.55535647, 0.54338602]])

# 3.Viewing arrays and matrices

In [32]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [33]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
a1[0], a2[0], a3[0]

(np.int64(1),
 array([1. , 2.3, 3. ]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [38]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [39]:
a3[:, :, 0]

array([[ 1,  4],
       [ 7, 10]])

In [40]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 2, 6, 8, 9],
         [3, 4, 5, 5, 7],
         [9, 2, 6, 9, 5],
         [1, 6, 4, 5, 8]],

        [[0, 7, 2, 6, 7],
         [4, 8, 9, 6, 4],
         [5, 2, 2, 6, 6],
         [6, 7, 9, 6, 0]],

        [[9, 2, 7, 9, 2],
         [6, 3, 0, 9, 0],
         [0, 6, 9, 7, 4],
         [7, 9, 4, 8, 2]]],


       [[[7, 2, 8, 6, 5],
         [2, 3, 3, 8, 7],
         [9, 7, 3, 8, 0],
         [7, 3, 0, 9, 0]],

        [[1, 2, 6, 7, 3],
         [8, 2, 9, 6, 5],
         [1, 3, 0, 0, 8],
         [6, 7, 8, 1, 0]],

        [[8, 9, 5, 2, 2],
         [2, 7, 7, 7, 6],
         [0, 3, 2, 4, 1],
         [5, 6, 3, 3, 0]]]])

In [41]:
a4.shape, a4.ndim, a4.size, a4.dtype

((2, 3, 4, 5), 4, 120, dtype('int64'))

In [42]:
a4[:, :, :1, :]

array([[[[2, 2, 6, 8, 9]],

        [[0, 7, 2, 6, 7]],

        [[9, 2, 7, 9, 2]]],


       [[[7, 2, 8, 6, 5]],

        [[1, 2, 6, 7, 3]],

        [[8, 9, 5, 2, 2]]]])

In [43]:
a4[1, 0, 0]

array([7, 2, 8, 6, 5])

# 4.Manipulating and Computing on NumPy Arrays

### Arithmetic

In [44]:
a1

array([1, 2, 3])

In [45]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [47]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [48]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [49]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [50]:
a1

array([1, 2, 3])

In [51]:
a1 + a2

array([[2. , 4.3, 6. ],
       [5. , 7. , 9. ]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
a2 * a3

array([[[ 1. ,  4.6,  9. ],
        [16. , 25. , 36. ]],

       [[ 7. , 18.4, 27. ],
        [40. , 55. , 72. ]]])

In [54]:
a4

array([[[[2, 2, 6, 8, 9],
         [3, 4, 5, 5, 7],
         [9, 2, 6, 9, 5],
         [1, 6, 4, 5, 8]],

        [[0, 7, 2, 6, 7],
         [4, 8, 9, 6, 4],
         [5, 2, 2, 6, 6],
         [6, 7, 9, 6, 0]],

        [[9, 2, 7, 9, 2],
         [6, 3, 0, 9, 0],
         [0, 6, 9, 7, 4],
         [7, 9, 4, 8, 2]]],


       [[[7, 2, 8, 6, 5],
         [2, 3, 3, 8, 7],
         [9, 7, 3, 8, 0],
         [7, 3, 0, 9, 0]],

        [[1, 2, 6, 7, 3],
         [8, 2, 9, 6, 5],
         [1, 3, 0, 0, 8],
         [6, 7, 8, 1, 0]],

        [[8, 9, 5, 2, 2],
         [2, 7, 7, 7, 6],
         [0, 3, 2, 4, 1],
         [5, 6, 3, 3, 0]]]])

In [55]:
# a2 + a4 error

In [56]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [57]:
a2_Fix = a2[:, :, np.newaxis, np.newaxis]
a2_Fix

array([[[[1. ]],

        [[2.3]],

        [[3. ]]],


       [[[4. ]],

        [[5. ]],

        [[6. ]]]])

In [58]:
a2_Fix + a4

array([[[[ 3. ,  3. ,  7. ,  9. , 10. ],
         [ 4. ,  5. ,  6. ,  6. ,  8. ],
         [10. ,  3. ,  7. , 10. ,  6. ],
         [ 2. ,  7. ,  5. ,  6. ,  9. ]],

        [[ 2.3,  9.3,  4.3,  8.3,  9.3],
         [ 6.3, 10.3, 11.3,  8.3,  6.3],
         [ 7.3,  4.3,  4.3,  8.3,  8.3],
         [ 8.3,  9.3, 11.3,  8.3,  2.3]],

        [[12. ,  5. , 10. , 12. ,  5. ],
         [ 9. ,  6. ,  3. , 12. ,  3. ],
         [ 3. ,  9. , 12. , 10. ,  7. ],
         [10. , 12. ,  7. , 11. ,  5. ]]],


       [[[11. ,  6. , 12. , 10. ,  9. ],
         [ 6. ,  7. ,  7. , 12. , 11. ],
         [13. , 11. ,  7. , 12. ,  4. ],
         [11. ,  7. ,  4. , 13. ,  4. ]],

        [[ 6. ,  7. , 11. , 12. ,  8. ],
         [13. ,  7. , 14. , 11. , 10. ],
         [ 6. ,  8. ,  5. ,  5. , 13. ],
         [11. , 12. , 13. ,  6. ,  5. ]],

        [[14. , 15. , 11. ,  8. ,  8. ],
         [ 8. , 13. , 13. , 13. , 12. ],
         [ 6. ,  9. ,  8. , 10. ,  7. ],
         [11. , 12. ,  9. ,  9. ,  6. ]]]])

In [59]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [60]:
a1 / a2

array([[1.        , 0.86956522, 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [61]:
a1 // a2 # Floor division removes the decimals (Rounds down)

array([[1., 0., 1.],
       [0., 0., 0.]])

In [62]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [63]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Aggregation
Aggregate = Performation the same operation on a number of things

In [64]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [65]:
sum(listy_list)

6

In [68]:
a1, type(a1), sum(a1)

(array([1, 2, 3]), numpy.ndarray, np.int64(6))

In [69]:
np.sum(a1)

np.int64(6)

Use Python's methods on python dataTypes (`sum()`) and use NumPy's methods on NumPy arrays (`np.sum()`)

In [70]:
# Create a massive NumPy array
massive_array = np.random.random(1000000)
massive_array.size

1000000

In [72]:
massive_array[: 10]

array([9.77171002e-01, 7.31568515e-01, 9.56283613e-02, 5.00606106e-01,
       4.62360079e-01, 7.43889443e-04, 9.88938940e-01, 8.77619941e-01,
       2.17211153e-01, 6.05377501e-01])

In [73]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

229 ms ± 15.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.62 ms ± 146 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [74]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [75]:
np.mean(a2), np.max(a2), np.min(a2)

(np.float64(3.5500000000000003), np.float64(6.0), np.float64(1.0))

In [76]:
# Standard Deviation = measure of how spread out a group of numbers is from the mean
np.std(a2)

np.float64(1.6670832812630167)

In [ ]:
# Variance = measure of how spread out a group of numbers is from the mean squared
# Higher variance means the data is more spread out
# Lower variance means the data is more clustered around the mean
np.var(a2)  

np.float64(2.779166666666667)

In [78]:
# Standard Deviation is the square root of Variance
np.sqrt(np.var(a2))

np.float64(1.6670832812630167)