## NumPy

In [1]:
import numpy as np

# DataType and Attributes

NumPy's main datatype is the ndarray (n-dimensional array).
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving 
the size of the array along each dimension.


In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a1.shape

(3,)

In [6]:
a1.dtype

dtype('int64')

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2.3, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 2, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from NumPy arrays

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.0
1  4.0  5.0  6.0

# 2. Creating Arrays

In [22]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [26]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
range_array = np.arange(0, 50, 5)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 9, 1, 1, 2],
       [4, 8, 6, 3, 9],
       [7, 9, 6, 7, 9]])

In [36]:
random_array.shape, random_array.size, random_array.ndim

((3, 5), 15, 2)

In [38]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.44177317, 0.73027341, 0.73764339],
       [0.52091118, 0.81195208, 0.69630233],
       [0.18602963, 0.37030625, 0.53994769],
       [0.51729473, 0.58562596, 0.95877459],
       [0.18590712, 0.85209984, 0.99875039]])

In [39]:
random_array2.shape, random_array2.size, random_array2.ndim

((5, 3), 15, 2)

In [40]:
random_array3 = np.random.rand(4, 2)
random_array3

array([[0.94978997, 0.55833967],
       [0.24985278, 0.3547447 ],
       [0.62963525, 0.42335529],
       [0.99739828, 0.4594713 ]])

In [41]:
random_array3.shape, random_array3.size, random_array3.ndim

((4, 2), 8, 2)

In [42]:
# Pseudo Random numbers
np.random.seed(0)