## NumPy

In [47]:
import numpy as np

# DataType and Attributes

NumPy's main datatype is the ndarray (n-dimensional array).
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving 
the size of the array along each dimension.


In [48]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [49]:
a1.shape

(3,)

In [50]:
a1.dtype

dtype('int64')

In [51]:
type(a1)

numpy.ndarray

In [52]:
a2 = np.array([[1, 2.3, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [53]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
a2.shape

(2, 3)

In [56]:
a3.shape

(2, 2, 3)

In [57]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [58]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [59]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [60]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from NumPy arrays

In [61]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.0
1  4.0  5.0  6.0

# 2. Creating Arrays

In [62]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [64]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
range_array = np.arange(0, 50, 5)
range_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [66]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0]])

In [67]:
random_array.shape, random_array.size, random_array.ndim

((3, 5), 15, 2)

In [68]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ]])

In [69]:
random_array2.shape, random_array2.size, random_array2.ndim

((5, 3), 15, 2)

In [70]:
random_array3 = np.random.rand(4, 2)
random_array3

array([[0.6176355 , 0.61209572],
       [0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 ]])

In [71]:
random_array3.shape, random_array3.size, random_array3.ndim

((4, 2), 8, 2)

In [72]:
# Pseudo Random numbers
# np.random.seed()

In [78]:
np.random.seed(0)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [84]:
np.random.seed(8)
random_array5 = np.random.random((3, 4))
random_array5

array([[0.8734294 , 0.96854066, 0.86919454, 0.53085569],
       [0.23272833, 0.0113988 , 0.43046882, 0.40235136],
       [0.52267467, 0.4783918 , 0.55535647, 0.54338602]])

# 3.Viewing arrays and matrices