## NumPy

In [1]:
import numpy as np

# DataType and Attributes

NumPy's main datatype is the ndarray (n-dimensional array).
It is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving 
the size of the array along each dimension.


In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a1.shape

(3,)

In [6]:
a1.dtype

dtype('int64')

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1, 2.3, 3], [4, 5, 6]])

a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
a2

array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 2, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 12)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Create a DataFrame from NumPy arrays

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.0
1  4.0  5.0  6.0